# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/air_quality_dashboard',
                'doc_host': 'https://st-augustine.github.io',
                'git_url': 'https://github.com/st-augustine/air_quality_dashboard',
                'lib_path': 'air_quality_dashboard'},
  'syms': {}}
